apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: lanchonete
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9sYW5jaG9uZXRlOiU0MExhbmNob25ldGUxMjNAbGFuY2hvbmV0ZS5qcGdtdC5tb25nb2RiLm5ldC9vcmRlcl9wYXltZW50P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUxhbmNob25ldGU="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: lanchonete
data:
  ORDER_URL: http://aecceb46beb6b431c8fd64ecbbf09bc8-1231354151.us-east-1.elb.amazonaws.com