apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-payment-hpa
  namespace: lanchonete
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
