apiVersion: v1
kind: Service
metadata:
  name: order-payment-service
  namespace: lanchonete
  labels:
    app: order-payment
    environment: production
spec:
  type: ClusterIP
  selector:
    app: order-payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
