apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: lanchonete
  labels:
    app: order-payment
    environment: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer
  selector:
    app: order-payment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080